version: '3.8'
services:
  spring-blog:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - POSTGRES_URL=jdbc:postgresql://psqlserver/BlogBase
    volumes:
      - ./:/app
    depends_on:
      - psqlserver

  psqlserver:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=devspring
      - POSTGRES_PASSWORD=devpass1
      - POSTGRES_DB=BlogBase
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_config:/var/lib/postgresql/data/postgresql.conf
volumes:
  postgres_data:
  postgres_config:
